name = "The One Modpack Server"
author = "j"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a73a697da478bd444a6e6b3fddea7f308b022a0c8896e6f3354b0dce71379101"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
