name = "The One Modpack Server"
author = "j"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "49e3040416274d0696caf669b22a69ebb7a9c3a79cf627d8a360efe99e712d53"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
