name = "The One Modpack Server"
author = "j"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c441b710a61616902581ed1b22efbacee06f2bb2d8093d734e412aa1abcbfa8d"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
