name = "The One Modpack Server"
author = "rj"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3d633685426edc4c919b7c1fc68fa57604637e7375ecb35637ba4e7f54e10344"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
