name = "The One Modpack Server"
author = "rj"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "31247c834cda353b399cd1b2037cbd23835ec2f71f9bd88ea6f38577fbe9a4f1"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
